# Generated by Django 5.2.5 on 2025-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction_category_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
